### ISSUE TITLE
The project does not run under Xcode 8.2

### ISSUE THREAD

**Issue by Zacch** [50ButtonsEach/ios-boilerplate-swift#2]
I let Xcode update the project to Swift 3 automatically, which seems to have worked. However, the compiler doesn't recognize the SCL classes. I get 7 errors like `ios-boilerplate-swift/AppDelegate.swift:46:14: Type 'SCLFlicManager' has no member 'sharedManager'`. Interestingly enough, if I type `SCLFlicManager.sh`, the editor will suggest "sharedManager" even though the compiler does not accept it.

Even if I use the unchanged project (with the build setting "Use Legacy Swift Language Version") I get seven compiler errors complaining about `SCLFlicManager.sharedManager`, `SCLFlicManager.configureWithDelegate` and `SCLFlicButton.color`.

**Comment by AntonMeier** [comment]
Ok, thanks for the heads up. I must admit that I have not yet tested this with Xcode 8.2 so it is possible that there may be some issues. I will take a look at it soon.

**Comment by AntonMeier** [comment]
I have now updated the project to support Swift 3 and Xcode 8.2.1. Please make sure that you also update to the latest fliclib.

**Comment by Zacch** [comment]
Thank you Anton,

That was quickly done! The project and the app now work perfectly.
